<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>Artwork_Change_Flyers</fullName>
        <description>Artwork Change- Flyers</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Artwork_Change_Flyers_1</fullName>
        <description>Artwork Change- Flyers</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Artwork_Change_Flyers_3</fullName>
        <description>Artwork Change- Flyers</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Artwork_Change_Flyers_4</fullName>
        <description>Artwork Change- Flyers</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Artwork_Change_Flyers_5</fullName>
        <description>Artwork Change- Flyers</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Artwork_Change_Flyers_6</fullName>
        <description>Artwork Change- Flyers</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Artwork_Change_Reminder_2</fullName>
        <description>Artwork Change Reminder- TAR</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportTAR</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Artwork_Change_Reminder_TAR</fullName>
        <description>Artwork Change Reminder- TAR</description>
        <protected>false</protected>
        <recipients>
            <recipient>dominique.carrier@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>kim.baloun@pni.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>mark.anthony@pni.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Artwork_Change_Reminder_TAR_3</fullName>
        <description>Artwork Change Reminder- TAR</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportTAR</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Artwork_Change_Reminder_TAR_4</fullName>
        <description>Artwork Change Reminder- TAR</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportTAR</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Artwork_Change_Reminder_TAR_7</fullName>
        <description>Artwork Change Reminder- TAR</description>
        <protected>false</protected>
        <recipients>
            <recipient>dominique.carrier@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>kim.baloun@pni.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>mark.anthony@pni.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Artwork_Change_Reminder_TAR_8</fullName>
        <description>Artwork Change Reminder- TAR</description>
        <protected>false</protected>
        <recipients>
            <recipient>dominique.carrier@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>kim.baloun@pni.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>mark.anthony@pni.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Artwork_Change_Date_Alert</fullName>
        <description>Customer Care Artwork Change Date Alert</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Artwork_Change_Date_Alert2</fullName>
        <description>Customer Care Artwork Change Date Alert2</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Artwork_Change_Date_Alert3</fullName>
        <description>Customer Care Artwork Change Date Alert</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Display_Art_Reminder</fullName>
        <description>Customer Care Display Art Reminder</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Display_Art_Reminder10</fullName>
        <description>Customer Care Display Art Reminder</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Display_Art_Reminder2</fullName>
        <description>Customer Care Display Art Reminder</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Display_Art_Reminder3</fullName>
        <description>Customer Care Display Art Reminder</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Display_Art_Reminder4</fullName>
        <description>Customer Care Display Art Reminder</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Display_Art_Reminder5</fullName>
        <description>Customer Care Display Art Reminder</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Display_Art_Reminder6</fullName>
        <description>Customer Care Display Art Reminder</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Display_Art_Reminder7</fullName>
        <description>Customer Care Display Art Reminder</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Display_Art_Reminder8</fullName>
        <description>Customer Care Display Art Reminder</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Customer_Care_Display_Art_Reminder9</fullName>
        <description>Customer Care Display Art Reminder</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Display_Art_Reminder_11</fullName>
        <description>Display Art Reminder 11</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Display_Art_Reminder_12</fullName>
        <description>Display Art Reminder 12</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Flyer_Drop_Date_Reminder2</fullName>
        <description>Flyer Drop Date Reminder</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Flyer_Drop_Date_Reminder</template>
    </alerts>
    <alerts>
        <fullName>New_Creative_Customer_Care</fullName>
        <description>New Creative - Customer Care</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/New_Creative_Customer_Care</template>
    </alerts>
    <alerts>
        <fullName>New_Creative_Customer_Care_TAR</fullName>
        <description>New Creative - Customer Care- TAR</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportTAR</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/New_Creative_Customer_Care</template>
    </alerts>
    <alerts>
        <fullName>Order_Entry_Complete</fullName>
        <description>Order Entry Complete</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupport</recipient>
            <type>group</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Order_Entry_Status_Complete</template>
    </alerts>
    <alerts>
        <fullName>ROP_Reminder_1</fullName>
        <description>ROP Reminder 1</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>ROP_Reminder_2</fullName>
        <description>ROP Reminder 2</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>ROP_Reminder_2_1</fullName>
        <description>ROP Reminder 2</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>ROP_Reminder_3</fullName>
        <description>ROP Reminder 3</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>ROP_Reminder_4</fullName>
        <description>ROP Reminder 4</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_1</fullName>
        <description>Valley Values - 1</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_1_1</fullName>
        <description>Valley Values - 1</description>
        <protected>false</protected>
        <recipients>
            <recipient>charley.eltringham@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>debra.sadowniczak@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>dominique.carrier@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>stephen.tong@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_1_v1</fullName>
        <description>Valley Values - 1</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_2</fullName>
        <description>Valley Values - 2</description>
        <protected>false</protected>
        <recipients>
            <recipient>charley.eltringham@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>debra.sadowniczak@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>dominique.carrier@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>stephen.tong@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_2_2</fullName>
        <description>Valley Values - 2</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_3</fullName>
        <description>Valley Values - 3</description>
        <protected>false</protected>
        <recipients>
            <recipient>charley.eltringham@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>debra.sadowniczak@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>dominique.carrier@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>stephen.tong@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_3_3</fullName>
        <description>Valley Values - 3</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_4</fullName>
        <description>Valley Values - 4</description>
        <protected>false</protected>
        <recipients>
            <recipient>charley.eltringham@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>debra.sadowniczak@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>dominique.carrier@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>stephen.tong@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_4_4</fullName>
        <description>Valley Values - 4</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_5</fullName>
        <description>Valley Values - 5</description>
        <protected>false</protected>
        <recipients>
            <recipient>charley.eltringham@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>debra.sadowniczak@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>dominique.carrier@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>stephen.tong@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_5_5</fullName>
        <description>Valley Values - 5</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_6</fullName>
        <description>Valley Values - 6</description>
        <protected>false</protected>
        <recipients>
            <recipient>charley.eltringham@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>debra.sadowniczak@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>dominique.carrier@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>stephen.tong@gannett.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <alerts>
        <fullName>Valley_Values_6_6</fullName>
        <description>Valley Values - 6</description>
        <protected>false</protected>
        <recipients>
            <recipient>AdSupportGLA</recipient>
            <type>role</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Opportunity_Templates/Valley_Values_Artwork_Change</template>
    </alerts>
    <fieldUpdates>
        <fullName>DListing_Address</fullName>
        <description>Prepops DListing Address</description>
        <field>Address__c</field>
        <formula>Opportunity__r.Account.BillingStreet</formula>
        <name>DListing - Address</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>DListing_City</fullName>
        <field>City__c</field>
        <formula>Opportunity__r.Account.BillingCity</formula>
        <name>DListing - City</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>DListing_Phone</fullName>
        <field>Phone__c</field>
        <formula>Opportunity__r.Account.Phone</formula>
        <name>DListing - Phone</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>DListing_State</fullName>
        <field>State__c</field>
        <formula>Opportunity__r.Account.BillingState</formula>
        <name>DListing - State</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>DListing_Website</fullName>
        <field>Web_Site__c</field>
        <formula>Opportunity__r.Account.Website</formula>
        <name>DListing - Website</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>DListing_Zip</fullName>
        <field>Zip_Code__c</field>
        <formula>Opportunity__r.Account.BillingPostalCode</formula>
        <name>DListing - Zip</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <rules>
        <fullName>Artwork Change 2</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Artwork_Change_Month_2__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <description>Fire when not equal to null</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Artwork_Change_Date_Alert2</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Artwork_Change_Month_2__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Artwork Change 3</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Artwork_Change_Month_3__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <description>Fire when not equal to null</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Artwork_Change_Date_Alert</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Artwork_Change_Month_3__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Artwork Change 4</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Artwork_Change_Month_4__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <description>Fire when not equal to null</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Artwork_Change_Date_Alert</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Artwork_Change_Month_4__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Artwork Change 5</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Artwork_Change_Month_5__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <description>Fire when not equal to null</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Artwork_Change_Date_Alert</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Artwork_Change_Month_5__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Artwork Change 6</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Artwork_Change_Month_6__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <description>Fire when not equal to null</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Artwork_Change_Date_Alert</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Artwork_Change_Month_6__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Artwork Change 7</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Artwork_Change_7_Reminder_Date__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <description>Fire when not equal to null</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Artwork_Change_Date_Alert3</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Artwork_Change_7_Reminder_Date__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Artwork Change Flyer- 3</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Artwork_Change_3_Flyers__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Artwork_Change_Flyers_3</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Artwork_Change_3_Flyers__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Artwork Change Flyer- 4</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Artwork_Change_4_Flyers__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Artwork_Change_Flyers_4</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Artwork_Change_4_Flyers__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Artwork Change Flyer- 5</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Artwork_Change_5_Flyers__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Artwork_Change_Flyers_5</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Artwork_Change_5_Flyers__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Artwork Change Flyer- 6</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Artwork_Change_6_Flyers__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Artwork_Change_Flyers_6</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Artwork_Change_6_Flyers__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Artwork Change Flyer-1</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Artwork_Change_1_Flyers__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Artwork_Change_Flyers_1</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Artwork_Change_1_Flyers__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Artwork Change Flyer-2</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Artwork_Change_2_Flyers__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Artwork_Change_Flyers</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Artwork_Change_2_Flyers__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>DListing - Address</fullName>
        <actions>
            <name>DListing_Address</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Address__c</field>
            <operation>equals</operation>
        </criteriaItems>
        <description>Passes Address info &quot;on save&quot; for DListing</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>DListing - City</fullName>
        <actions>
            <name>DListing_City</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.City__c</field>
            <operation>equals</operation>
        </criteriaItems>
        <description>Fire to Customer Care when city is null</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>DListing - Phone</fullName>
        <actions>
            <name>DListing_Phone</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Phone__c</field>
            <operation>equals</operation>
        </criteriaItems>
        <description>Fire to Customer Care when phone is null</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>DListing - State</fullName>
        <actions>
            <name>DListing_State</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.State__c</field>
            <operation>equals</operation>
        </criteriaItems>
        <description>Fire to Customer Care when state is null</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>DListing - Website</fullName>
        <actions>
            <name>DListing_Website</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Web_Site__c</field>
            <operation>equals</operation>
        </criteriaItems>
        <description>Fire to Customer Care when website is null</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>DListing - Zip</fullName>
        <actions>
            <name>DListing_Zip</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Zip_Code__c</field>
            <operation>equals</operation>
        </criteriaItems>
        <description>Fire when zip code is null</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>Display Art Reminder 1</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Display_Art_Reminder__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Display_Art_Reminder</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Display_Art_Reminder__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Display Art Reminder 10</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Display_Art_Reminder_10__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Display_Art_Reminder10</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Display_Art_Reminder_10__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Display Art Reminder 11</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Display_Art_Reminder_11__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Display_Art_Reminder_11</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Display_Art_Reminder_11__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Display Art Reminder 12</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Display_Art_Reminder_12__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Display_Art_Reminder_12</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Display_Art_Reminder_12__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Display Art Reminder 2</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Display_Art_Reminder_2__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Display_Art_Reminder2</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Display_Art_Reminder_2__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Display Art Reminder 3</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Display_Art_Reminder_3__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Display_Art_Reminder3</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Display_Art_Reminder_3__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Display Art Reminder 4</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Display_Art_Reminder_4__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Display_Art_Reminder4</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Display_Art_Reminder_4__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Display Art Reminder 5</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Display_Art_Reminder_5__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Display_Art_Reminder5</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Display_Art_Reminder_5__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Display Art Reminder 6</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Display_Art_Reminder_6__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Display_Art_Reminder6</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Display_Art_Reminder_6__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Display Art Reminder 7</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Display_Art_Reminder_7__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Display_Art_Reminder7</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Display_Art_Reminder_7__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Display Art Reminder 8</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Display_Art_Reminder_8__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Display_Art_Reminder8</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Display_Art_Reminder_8__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Display Art Reminder 9</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Display_Art_Reminder_9__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Customer_Care_Display_Art_Reminder9</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Display_Art_Reminder_9__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Flyer Drop Date Reminder</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Drop_Date__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <criteriaItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>TAR Active</value>
        </criteriaItems>
        <description>Fire when drop date not equal to null</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Flyer_Drop_Date_Reminder2</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Drop_Date__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Order Entry Status- Complete</fullName>
        <actions>
            <name>Order_Entry_Complete</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Order_Entry_Status__c</field>
            <operation>equals</operation>
            <value>Entered/Complete</value>
        </criteriaItems>
        <criteriaItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>TAR Active</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>Post Won - Community Print Order Change</fullName>
        <actions>
            <name>New_Creative_Customer_Care</name>
            <type>Alert</type>
        </actions>
        <actions>
            <name>Customer_Care_Action_Creative_Print_Change</name>
            <type>Task</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Order_Entry_Status__c</field>
            <operation>equals</operation>
            <value>New/Pending</value>
        </criteriaItems>
        <criteriaItems>
            <field>Order_Fulfillment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Community Print</value>
        </criteriaItems>
        <criteriaItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </criteriaItems>
        <criteriaItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>contains</operation>
            <value>SML Opportunity,Nashville Opportunity,Burlington</value>
        </criteriaItems>
        <description>Closed Won Opp, new Community Print order (change) is created.</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>Post Won - Community Print Order Change- TAR</fullName>
        <actions>
            <name>New_Creative_Customer_Care_TAR</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Order_Entry_Status__c</field>
            <operation>equals</operation>
            <value>New/Pending</value>
        </criteriaItems>
        <criteriaItems>
            <field>Order_Fulfillment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Community Print</value>
        </criteriaItems>
        <criteriaItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </criteriaItems>
        <criteriaItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>contains</operation>
            <value>TAR Active</value>
        </criteriaItems>
        <description>Closed Won Opp, new Community Print order (change) is created.</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ROP Reminder 1</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.ROP_Reminder_1__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>ROP_Reminder_1</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.ROP_Reminder_1__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>ROP Reminder 2</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.ROP_Reminder_2__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>ROP_Reminder_2_1</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.ROP_Reminder_2__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>ROP Reminder 3</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.ROP_Reminder_3__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>ROP_Reminder_3</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.ROP_Reminder_3__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>ROP Reminder 4</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.ROP_Reminder_4__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>ROP_Reminder_4</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.ROP_Reminder_4__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>ROP Reminder 5</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.ROP_Reminder_5__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <offsetFromField>Order_Fulfillment__c.ROP_Reminder_5__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>ROP Reminder 6</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.ROP_Reminder_6__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <offsetFromField>Order_Fulfillment__c.ROP_Reminder_6__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Valley Values - 1</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Valley_Values_1__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Valley_Values_1_v1</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Valley_Values_1__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Valley Values - 2</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Valley_Values_2__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Valley_Values_2_2</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Valley_Values_2__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Valley Values - 3</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Valley_Values_3__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Valley_Values_3_3</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Valley_Values_3__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Valley Values - 4</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Valley_Values_4__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Valley_Values_4_4</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Valley_Values_4__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Valley Values - 5</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Valley_Values_5__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Valley_Values_5_5</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Valley_Values_5__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>Valley Values - 6</fullName>
        <active>true</active>
        <criteriaItems>
            <field>Order_Fulfillment__c.Valley_Values_6__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Valley_Values_6_6</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Order_Fulfillment__c.Valley_Values_6__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <tasks>
        <fullName>Customer_Care_Action_Creative_Print_Change</fullName>
        <assignedTo>melanie.ricotta@gannett.com</assignedTo>
        <assignedToType>user</assignedToType>
        <description>A new Community Print Order Fulfillment record has been created, associated to an existing &quot;Closed Won&quot; Opportunity.</description>
        <dueDateOffset>0</dueDateOffset>
        <notifyAssignee>false</notifyAssignee>
        <priority>High</priority>
        <protected>false</protected>
        <status>Not Started</status>
        <subject>Customer Care Action - Creative Print Change</subject>
    </tasks>
</Workflow>
