<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <classAccesses>
        <apexClass>OnBoardFormBeforeInsertTriggerHandler</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>OnBoardFormControllerExt</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <fieldPermissions>
        <editable>false</editable>
        <field>OnBoardFormModel__c.LCP_Product_Order_Id__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>OnBoardFormModel__c.MNR_Product_Order_Id__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>OnBoardFormModel__c.PPC_Product_Order_Id__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>OnBoardFormModel__c.SEO_Product_Order_Id__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>OnBoardFormModel__c.SocAd_Product_Order_Id__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>OnBoardFormModel__c.SocMgmt_Product_Order_Id__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>OnBoardFormModel__c.TEmail_Product_Order_Id__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>OnBoardFormModel__c.WEB_Product_Order_Id__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>OpportunityLineItem.Product_Order_Id__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <layoutAssignments>
        <layout>OnBoardFormModel__c-OnBoardFormModel Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>OpportunityLineItem-Opportunity Product Layout - Billing</layout>
    </layoutAssignments>
    <loginHours/>
    <pageAccesses>
        <apexPage>OnBoardForm</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <userLicense>Salesforce</userLicense>
</Profile>
