public class LeadBeforeDeleteTriggerHandler extends TriggerHandlerBase {
    
    public override void mainEntry(TriggerParameters tp) {
        
    }
    
    private void process(List<SObject> listObjects) {
        
    }
    
    public override void inProgressEntry(TriggerParameters tp) {
        
    }
    
    public override void updateObjects() {
        
    }
    
    /* 
                        ----------- BEGIN CODE TRANSPLANT -----------------
    */
    
}