@CHARSET "ISO-8859-1";

.ppc-section-title {
	color: black;
	font-size: 16px;
	font-weight: bold;
	clear: both;
	padding-top:15px
}

.ppc-section-break {
	width: 800px !important;
	border-bottom: 2px solid black;
	padding-bottom:5px;
	padding-top:5px
	clear: both;
	margin-bottom:20px;
}

.ppc-section-content {
	margin-left:5px;
	width: 800px !important;
}

.ppc-field-label {
	font-size: 12px;
	font-weight: bold;
	float:left;
	width: 260px;
	margin-bottom:5px;
}

.smallerlabel {
	width: 145px !important;
}
.biggerlabel {
	width: 300px !important;
}
.smalllabel {
	width: 230px !important;
}

.ppc-field-content {
	font-size: 12px;
	float:left;
	width: 260px;
	margin-bottom:5px;
}

.smallercontent {
	width: 230px;
}

.newline {
	clear: both;
}

.spacermargin {
	margin-top:15px;
	margin-bottom:10px;
}

.bigmargin {
	margin-top:30px;
	margin-bottom:10px;
	width: auto !important;
}
.bigmargin2 {
	margin-top:25px;
	margin-left:10px;
	margin-bottom:10px;
	width: auto !important;
}

.biggerfont {
	font-size: 14px;
}

.graybox {
	width: 230px;
	margin-right:28px;
	background-color:white;
	height:18px;
}


.budget-label {
	width:180px !important;
}

.graybox span {
	margin: 4px;
	line-height:18px;
}
.ppc-input-small {
	width:220px;
}
.ppc-input-normal {
	width:230px;
}

.ppc-input-normal {
	width:230px;
}

.ppc-input-full {
	width: 800px !important;
}

.ppc-location {
	margin-top:20px;
	margin-right:8px;
	float:left;
	background-color: #FFFFFF;
	padding: 3px;
	border: 1px solid #E0E3E5;
}

table.ppc-spend-schedule-table {
	font-family: verdana,arial,sans-serif;
	font-size:12px;
	color:#333333;
	border-width: 1px;
	border-color: #666666;
	border-collapse: collapse;
	table-layout: fixed; 
	width: 800px; 
}
table.ppc-spend-schedule-table th {
	border-width: 1px;
	padding: 6px;
	border-style: solid;
	border-color: #666666;
	background-color: #dedede;
	width: 33% !important;
}
table.ppc-spend-schedule-table td {
	border-width: 1px;
	padding: 6px;
	font-size: 13px;
	border-style: solid;
	border-color: #666666;
	background-color: #ffffff;
}

.alignright {
	text-align: right;
}
.aligncenter {
	text-align: center;
	vertical-align: middle !important;
}

.smallfont {
	font-size:12px;
	font-weight: normal;
}
.requiredfield {
	color: #CC0000;
}
.duplicateMessage
{
	font-weight: bold;
}
.duplicateMessage p
{
	color: #CC0000;
	padding-bottom:8px;
	font-size: 14px;
}
.duplicateMessage span
{
	width: 500px !important;
	color: #000080;
	display:block;
}

#ppcSpendTable .requiredInput .requiredBlock {
	background-color: #FFFFFF;
}

.ui-combobox { display: inline-block; margin: 0; margin-right: 1.8em; position: relative; }
.ui-combobox-input { padding: 0.2em; margin: 0; }
.ui-combobox-button { position: absolute; width: 1.8em !important; margin: 0; margin-left: -1px; top: 0; bottom: 0; }
.ui-combobox-button .ui-button-text { padding: 0em; }
.ui-combobox .ui-autocomplete { max-height: 10em; overflow-y: auto; overflow-x: hidden; }